openapi: 3.0.0
info: 
  title: To-do API
  description: To-do app api
  version: '1.0'
  
paths: 
  /user/todos:
    get:
      summary: Return list of to-do
      responses:
        '200':
          description: To-do array
          content: 
            application/json:
              schema:
                items:
                  content: 
                  $ref: '#/components/schemas/ToDoBundleResponse'
        '404':
          description: To-dos cannot found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error400'
        '500':
          description: Server error
    post:
      summary: Create a to-do
      requestBody:
        description: Enter the values to create a to-do
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToDoResponse'
      responses:
        '200':
          description: Create a to-do
          content:
            application/json:
              schema:
                type: string
                content:
                $ref: '#/components/schemas/ToDoResponse'
        '500':
          description: server error
  /user/todos/{todoID}:
    get:
      summary: Returns a to-do by ID.
      parameters: 
        - name: todoID
          in: path
          required: true
          description: ID Parameter of to-do that you wanted the display
          schema:
            $ref: '#/components/schemas/ToDoResponse'
      responses:
        '200':
          description: To-do displayed
          content:
            application/json:
              schema:
                type: string
                content:
                $ref: '#/components/schemas/ToDoResponse'
        '404':
          description: To-do cannot found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error400'
        '500':
          description: server error
    delete:
      summary: Delete a to-do by ID
      parameters: 
        - name: todoID
          in: path
          required: true
          description: Parameter of to-do that you wanted the delete
          schema:
            $ref: '#/components/schemas/ToDoResponse'
      responses:
        '200':
          description: To-do deleted
          content:
            application/json:
              schema:
                type: string
                content:
                $ref: '#/components/schemas/ToDoResponse'
        '404':
          description: To-do cannot found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error400'
        '500':
          description: server error
  /user/todos/{todoDetail}:
    patch:
      summary: Update to-do Detail
      parameters:
        - name: todoDetail
          in: path
          required: true
          description: Parameter of to-do that you wanted the update
          schema:
            $ref: '#/components/schemas/ToDoResponse'
      responses:
        '200':
          description: To-do detail updated
          content:
            application/json:
              schema:
                type: string
                content:
                $ref: '#/components/schemas/ToDoResponse'
        '404':
          description: Requested to-do's detail not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error400'
  /user/todos/{todoStatus}:
    patch:
      summary: Update to-do Status
      parameters:
        - name: todoStatus
          in: path
          required: true
          description: Parameter of to-do that you wanted the update
          schema:
            $ref: '#/components/schemas/ToDoResponse'
      responses:
        '200':
          description: To-do status updated
          content:
            application/json:
              schema:
                type: string
                content:
                $ref: '#/components/schemas/ToDoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error400'
        '500':
          description: Server Error

components: 
  schemas:
    ToDoResponse:
      title: To-Do
      properties:
        id:
          type: integer
        details:
          type: string
        status:
          type: string
          enum:
            - to-Do
            - on progress
            - done
    ToDoBundleResponse:
      allOf:
        - $ref: '#/components/schemas/ToDoResponse'
    error400:
      properties:
        message:
          default: 
            Geçersiz bir istek gönderdiniz