openapi: 3.0.0
info: 
  title: To-do API
  description: To-do app api
  version: '1.0'
  
paths: 
  /to-dos:
    get:
      summary: Return list of to-do
      responses:
        '200':
          description: A Json array of to-dos
          content: 
            application/json:
              schema:
                type: array
                items:
                  content: 
                  $ref: '#/components/schemas/to-do'
        '301':
          description: Requested url moved
    post:
      summary: Create a to-do
      requestBody:
        description: Enter the values to create a to-do
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/to-do2'
      responses:
        '200':
          description: Create a to-do
          content:
            application/json:
              schema:
                type: string
                content:
                $ref: '#/components/schemas/to-do'
        '500':
          description: server error
  /to-dos/{to-doID}:
    get:
      summary: Returns a to-do by ID.
      parameters: 
        - name: to-doID
          in: path
          required: true
          description: Parameter of to-do that you wanted the display
          schema:
            $ref: '#/components/schemas/to-do'
      responses:
        '200':
          description: Parameters Displayed
          content:
            application/json:
              schema:
                type: string
                content:
                $ref: '#/components/schemas/to-do'
        '500':
          description: server error
    delete:
      summary: Delete a to-do by ID
      parameters: 
        - name: to-doID
          in: path
          required: true
          description: Parameter of to-do that you wanted the display
          schema:
            $ref: '#/components/schemas/to-do'
      responses:
        '200':
          description: Json object deleted
          content:
            application/json:
              schema:
                type: string
                content:
                $ref: '#/components/schemas/to-do'
        '500':
          description: server error
  /to-dos/{to-doDetail}:
    patch:
      summary: Update to-do Detail
      parameters:
        - name: to-doDetail
          in: path
          required: true
          description: Parameter of to-do that you wanted the update
          schema:
            $ref: '#/components/schemas/to-do/properties/details'
      responses:
        '200':
          description: A Json object of to-do
          content:
            application/json:
              schema:
                type: string
                content:
                $ref: '#/components/schemas/to-do/properties/details'
        '404':
          description: Requested to-do's detail not found
  /to-dos/{to-doStatus}:
    patch:
      summary: Update to-do Status
      parameters:
        - name: to-doStatus
          in: path
          required: true
          description: Parameter of to-do that you wanted the update
          schema:
            $ref: '#/components/schemas/to-do/properties/status'
      responses:
        '200':
          description: A Json object of to-do
          content:
            application/json:
              schema:
                type: string
                content:
                $ref: '#/components/schemas/to-do/properties/details'
        '500':
          description: server error
    
components: 
  schemas:
    to-do:
      title: to-do
      properties:
        id:
          type: integer
          example: 13
        details:
          type: string
          example: Do the swagger doc
        status:
          type: string
          example: done
    to-do2:
      title: to-do
      properties:
        id:
          type: integer
          example: 0
        details:
          type: string
          example: to-do app
        status:
          type: string
          example: undone
      
  