CREATE TABLE users (
    "user_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" varchar NOT NULL,
    "password" varchar NOT NULL,
    "status" varchar NOT NULL,
    "created_at" timestamp NOT NULL DEFAULT (now()),
    "updated_at" timestamp NOT NULL DEFAULT (now()),
    "deleted_at" timestamp
);

CREATE TABLE to_dos (
    "todo_id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" int NOT NULL,
    "details" varchar NOT NULL,
    "status" varchar NOT NULL,
    "created_at" timestamp NOT NULL DEFAULT (now()),
    "updated_at" timestamp NOT NULL DEFAULT (now()),
    CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(user_id)
);