CREATE TABLE users (
    "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "email" varchar NOT NULL,
    "password" varchar NOT NULL,
    "status" varchar NOT NULL,
    "created_at" timestamp NOT NULL DEFAULT (now()),
    "updated_at" timestamp NOT NULL DEFAULT (now()),
    "deleted_at" timestamp
);

ALTER TABLE to_dos RENAME COLUMN todo_id TO id;

ALTER TABLE to_dos ADD COLUMN user_id INTEGER NOT NULL;

ALTER TABLE to_dos ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id);
